apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploycart-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Filopateer-Shaker/DeployCart.git
    targetRevision: main
    path: helm/backend
    helm:
      releaseName: backend
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
